import type { ImportBatch } from "@/lib/importStore";

export function buildInitialBatches(): ImportBatch[] {
  const uploadedAt = "2026-06-08T13:44:34.000Z";

  return [
    {
      id: "IMB-DEMO-001",
      fileName: "Sampling Data for System Demo (1).xlsx",
      sourceSheetName: "Item Vendor Tracking",
      sourceHeaderRowNumber: 3,
      uploadedBy: "Operations Desk",
      uploadedAt,
      stage: "Assignment in progress",
      progressPercent: 40,
      validationStatus: "blocked",
      importJob: null,
      assignmentRules: [],
      assignmentDraft: null,
      dispatchRuns: [],
      rows: [
        {
          id: "IMR-001",
          sheetRowNumber: 12,
          raw: {
            poNumber: "5701713444",
            poLine: "1",
            cycle: "Cycle 3",
            year: "2026",
            zone: "West",
            region: "Jakarta Inner",
            area: "Depok",
            wcode: "WH059",
            salesPoint: "Depok",
            itemName: "TPOSM - Sunscreen Without Velcro - 0.5x1 m - Vinyl FF Frontlight 10 Oz - DPP12 20K",
            category: "POSM",
            itemCode: "TPOSM-SC-001",
            brand: "Sunscreen",
            brandSku: "SC-001",
            brandNamePo: "DPP12 20K",
            length: "0.5",
            width: "1",
            quantity: "10",
            orderDate: "2026-06-02",
            productionStartDate: "2026-06-06",
            productionFinishDate: "2026-06-10",
            shipmentDate: "2026-06-12",
            estReceivedDate: "2026-06-14",
            receivedDateBasedOnCpt: "",
            dnNumber: "",
            entity: "PT HM Sampoerna Tbk",
            linkFa: "",
          },
          quantity: 10,
          status: "unassigned",
          match: {
            productCode: "TPOSM-SC-001",
            productName: "TPOSM - Sunscreen Without Velcro - 0.5x1 m - Vinyl FF Frontlight 10 Oz - DPP12 20K",
            salesPointId: "WH059",
            salesPointName: "Depok",
            clientId: "CLNT-001",
            clientName: "Sampoerna",
            clientEntityName: "PT HM Sampoerna Tbk",
            companyName: "Sampoerna",
            brandName: "Sunscreen",
            categoryName: "POSM",
            issues: [],
          },
          possibleDuplicate: false,
          duplicateKey: "5701713444|1|wh059|depok|tposm-sc-001|tposm - sunscreen without velcro - 0.5x1 m - vinyl ff frontlight 10 oz - dpp12 20k|10",
          idempotencyKey: "imb-demo-001::5701713444|1|wh059|depok|tposm-sc-001|tposm - sunscreen without velcro - 0.5x1 m - vinyl ff frontlight 10 oz - dpp12 20k|10::12",
          duplicateWith: [],
          duplicateDecision: "include",
          assignment: null,
          excludedReason: null,
          dispatchedOrderId: null,
        },
        {
          id: "IMR-002",
          sheetRowNumber: 13,
          raw: {
            poNumber: "5701713444",
            poLine: "2",
            cycle: "Cycle 3",
            year: "2026",
            zone: "West",
            region: "Jakarta Inner",
            area: "Depok",
            wcode: "WH059",
            salesPoint: "Depok",
            itemName: "Shelf Strip Highlight",
            category: "POSM",
            itemCode: "TPOSM-AM-024",
            brand: "A Mild",
            brandSku: "AM-024",
            brandNamePo: "A Mild",
            length: "1",
            width: "0.2",
            quantity: "24",
            orderDate: "2026-06-02",
            productionStartDate: "2026-06-06",
            productionFinishDate: "2026-06-10",
            shipmentDate: "2026-06-12",
            estReceivedDate: "2026-06-14",
            receivedDateBasedOnCpt: "",
            dnNumber: "",
            entity: "PT HM Sampoerna Tbk",
            linkFa: "",
          },
          quantity: 24,
          status: "assigned",
          match: {
            productCode: "TPOSM-AM-024",
            productName: "Shelf Strip Highlight",
            salesPointId: "WH059",
            salesPointName: "Depok",
            clientId: "CLNT-001",
            clientName: "Sampoerna",
            clientEntityName: "PT HM Sampoerna Tbk",
            companyName: "Sampoerna",
            brandName: "A Mild",
            categoryName: "POSM",
            issues: [],
          },
          possibleDuplicate: false,
          duplicateKey: "5701713444|2|wh059|depok|tposm-am-024|shelf strip highlight|24",
          idempotencyKey: "imb-demo-001::5701713444|2|wh059|depok|tposm-am-024|shelf strip highlight|24::13",
          duplicateWith: [],
          duplicateDecision: "include",
          assignment: {
            vendorId: "SUP-004",
            vendorName: "PT. HH Global Services Indonesia",
            assignedAt: uploadedAt,
            assignedBy: "Admin Dispatch Workspace",
          },
          excludedReason: null,
          dispatchedOrderId: null,
        },
        {
          id: "IMR-003",
          sheetRowNumber: 14,
          raw: {
            poNumber: "5701713499",
            poLine: "1",
            cycle: "Cycle 3",
            year: "2026",
            zone: "West",
            region: "Jakarta Outer",
            area: "Bogor",
            wcode: "WH021",
            salesPoint: "Bogor",
            itemName: "Counter Display Kit",
            category: "Display",
            itemCode: "TPOSM-CD-404",
            brand: "Dji Sam Soe",
            brandSku: "DSS-404",
            brandNamePo: "Dji Sam Soe",
            length: "1",
            width: "1",
            quantity: "6",
            orderDate: "2026-06-03",
            productionStartDate: "2026-06-07",
            productionFinishDate: "2026-06-11",
            shipmentDate: "2026-06-13",
            estReceivedDate: "2026-06-15",
            receivedDateBasedOnCpt: "",
            dnNumber: "",
            entity: "PT HM Sampoerna Tbk",
            linkFa: "",
          },
          quantity: 6,
          status: "unresolved",
          match: {
            productCode: null,
            productName: null,
            salesPointId: "WH021",
            salesPointName: "Bogor",
            clientId: "CLNT-001",
            clientName: "Sampoerna",
            clientEntityName: "PT HM Sampoerna Tbk",
            companyName: "Sampoerna",
            brandName: "Dji Sam Soe",
            categoryName: "Display",
            issues: ["Item code not found in product master", "Review vendor-ready substitute"],
          },
          possibleDuplicate: false,
          duplicateKey: "5701713499|1|wh021|bogor|tposm-cd-404|counter display kit|6",
          idempotencyKey: "imb-demo-001::5701713499|1|wh021|bogor|tposm-cd-404|counter display kit|6::14",
          duplicateWith: [],
          duplicateDecision: "include",
          assignment: {
            vendorId: "SUP-002",
            vendorName: "RouteCraft Visual",
            assignedAt: uploadedAt,
            assignedBy: "Admin Dispatch Workspace",
          },
          excludedReason: null,
          dispatchedOrderId: null,
        },
        {
          id: "IMR-004",
          sheetRowNumber: 15,
          raw: {
            poNumber: "5701713503",
            poLine: "1",
            cycle: "Cycle 3",
            year: "2026",
            zone: "West",
            region: "Jakarta Inner",
            area: "Menteng",
            wcode: "WH001",
            salesPoint: "Menteng",
            itemName: "Hanging Mobile Banner",
            category: "POSM",
            itemCode: "TPOSM-HM-018",
            brand: "Marlboro",
            brandSku: "MB-018",
            brandNamePo: "Marlboro",
            length: "1",
            width: "0.4",
            quantity: "18",
            orderDate: "2026-06-03",
            productionStartDate: "2026-06-07",
            productionFinishDate: "2026-06-11",
            shipmentDate: "2026-06-13",
            estReceivedDate: "2026-06-15",
            receivedDateBasedOnCpt: "",
            dnNumber: "",
            entity: "PT HM Sampoerna Tbk",
            linkFa: "",
          },
          quantity: 18,
          status: "assigned",
          match: {
            productCode: "TPOSM-HM-018",
            productName: "Hanging Mobile Banner",
            salesPointId: "WH001",
            salesPointName: "Menteng",
            clientId: "CLNT-001",
            clientName: "Sampoerna",
            clientEntityName: "PT HM Sampoerna Tbk",
            companyName: "Sampoerna",
            brandName: "Marlboro",
            categoryName: "POSM",
            issues: [],
          },
          possibleDuplicate: true,
          duplicateKey: "5701713503|1|wh001|menteng|tposm-hm-018|hanging mobile banner|18",
          idempotencyKey: "imb-demo-001::5701713503|1|wh001|menteng|tposm-hm-018|hanging mobile banner|18::15",
          duplicateWith: ["Existing order"],
          duplicateDecision: "pending",
          assignment: {
            vendorId: "SUP-003",
            vendorName: "Metro Printworks",
            assignedAt: uploadedAt,
            assignedBy: "Admin Dispatch Workspace",
          },
          excludedReason: null,
          dispatchedOrderId: null,
        },
        {
          id: "IMR-005",
          sheetRowNumber: 16,
          raw: {
            poNumber: "5701713510",
            poLine: "1",
            cycle: "Cycle 3",
            year: "2026",
            zone: "Central",
            region: "Bandung",
            area: "Bandung",
            wcode: "WH077",
            salesPoint: "Bandung",
            itemName: "Window Takeover Strip",
            category: "POSM",
            itemCode: "TPOSM-WT-014",
            brand: "Sampoerna Kretek",
            brandSku: "SK-014",
            brandNamePo: "Sampoerna Kretek",
            length: "2",
            width: "0.3",
            quantity: "14",
            orderDate: "2026-06-04",
            productionStartDate: "2026-06-08",
            productionFinishDate: "2026-06-12",
            shipmentDate: "2026-06-14",
            estReceivedDate: "2026-06-16",
            receivedDateBasedOnCpt: "",
            dnNumber: "",
            entity: "PT HM Sampoerna Tbk",
            linkFa: "",
          },
          quantity: 14,
          status: "dispatched",
          match: {
            productCode: "TPOSM-WT-014",
            productName: "Window Takeover Strip",
            salesPointId: "WH077",
            salesPointName: "Bandung",
            clientId: "CLNT-001",
            clientName: "Sampoerna",
            clientEntityName: "PT HM Sampoerna Tbk",
            companyName: "Sampoerna",
            brandName: "Sampoerna Kretek",
            categoryName: "POSM",
            issues: [],
          },
          possibleDuplicate: false,
          duplicateKey: "5701713510|1|wh077|bandung|tposm-wt-014|window takeover strip|14",
          idempotencyKey: "imb-demo-001::5701713510|1|wh077|bandung|tposm-wt-014|window takeover strip|14::16",
          duplicateWith: [],
          duplicateDecision: "include",
          assignment: {
            vendorId: "SUP-004",
            vendorName: "PT. HH Global Services Indonesia",
            assignedAt: uploadedAt,
            assignedBy: "Admin Dispatch Workspace",
          },
          excludedReason: null,
          dispatchedOrderId: "OR-2026-555555",
        },
      ],
    },
  ];
}

export const initialSeedBatches = buildInitialBatches();
