// Auto-generated from docs/masterdata/Master_PIC_Address.csv (136 rows) + 2 stub entries from addresses_cleaned.csv
// Do not edit manually

export interface SalesPointPic {
  name: string;
  email: string;
  phone: string;
}

export interface ShippingAddress {
  provinsi: string;
  kotaKabupaten: string;
  kecamatan: string;
  alamat: string;
  kodePos: string;
}

export interface SalesPointSeed {
  zone: string;
  region: string;
  area: string;
  subArea: string;
  pic1: SalesPointPic;
  pic2: SalesPointPic;
  remarks: string;
  note: string;
  shippingAddress: ShippingAddress;
}

export const salesPointSeeds: SalesPointSeed[] = [
  {
    zone: "Central Java",
    region: "Java 2",
    area: "Madiun",
    subArea: "Madiun",
    pic1: { name: "MAYA MAYANUAR", email: "maya.mayanuar@panamas.com", phone: "0812 2530 794" },
    pic2: { name: "R.A Adbilla", email: "Abdilla.R.A@contracted.sampoerna.com", phone: "08979274042" },
    remarks: "PIC 1 ARA PIC 2 Logistik",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Timur",
      kotaKabupaten: "Madiun",
      kecamatan: "",
      alamat: "Jl Raya Nglemes no 130, Kab Madiun, Jatim",
      kodePos: "",
    },
  },
  {
    zone: "Central Java",
    region: "Java 2",
    area: "Magelang",
    subArea: "Magelang",
    pic1: { name: "ASEP NURSYAHID", email: "asep.nursyahid@panamas.com", phone: "08112774420" },
    pic2: { name: "Utomo Yulius Priyo Setyo", email: "YuliusPriyoSetyo.Utomo@contracted.sampoerna.com", phone: "089510350012" },
    remarks: "PIC 1 ARA PIC 2 Logistik",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Tengah",
      kotaKabupaten: "Magelang Provinsi Jawa Tengah - 56125",
      kecamatan: "Magelang Selatan",
      alamat: "Jl. Soekarno - Hatta No.12, Kel. Tidar Selatan Kec. Magelang Selatan, Kab. Magelang Provinsi Jawa Tengah - 56125",
      kodePos: "56125",
    },
  },
  {
    zone: "Central Java",
    region: "Java 2",
    area: "Purwokerto",
    subArea: "DPC Cilacap",
    pic1: { name: "ZEIN HILMAN SULTONY", email: "zeinhilman.sultony@panamas.com", phone: "08113039234" },
    pic2: { name: "Agus Deka", email: "Deka.Agus@contracted.sampoerna.com", phone: "085716251558" },
    remarks: "PIC 1 ARA PIC 2 Logistik",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Tengah",
      kotaKabupaten: "Cilacap Jawa Tengah 53252",
      kecamatan: "Jeruklegi Kab. Cilacap Jawa Tengah 53252",
      alamat: "PT HM Sampoerna Cilacap Jl. Raya Jeruk legi RT 005 RW 002 Desa Jeruklegi Wetan, Kec. Jeruklegi Kab. Cilacap Jawa Tengah 53252",
      kodePos: "53252",
    },
  },
  {
    zone: "Central Java",
    region: "Java 2",
    area: "Purwokerto",
    subArea: "Purwokerto",
    pic1: { name: "ZEIN HILMAN SULTONY", email: "zeinhilman.sultony@panamas.com", phone: "08113039234" },
    pic2: { name: "Gigien Finisyanto", email: "Gigien.Finisyanto@contracted.sampoerna.com", phone: "085741990072" },
    remarks: "PIC 1 ARA PIC 2 Logistik",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "PT. HM Sampoerna Tbk, Jl. Geriliya Timur N0. 54, Berkoh, Purwokerto - BAnyumas.",
      kodePos: "",
    },
  },
  {
    zone: "Central Java",
    region: "Java 2",
    area: "Salatiga",
    subArea: "Salatiga",
    pic1: { name: "DANANG HARI WIBOWO", email: "dananghari.wibowo@panamas.com", phone: "08112712828" },
    pic2: { name: "Petrus Haryono", email: "Tri.Kurnianingsih@contracted.sampoerna.com", phone: "082146931578" },
    remarks: "PIC 1 ARA PIC 2 Logistik",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Tengah",
      kotaKabupaten: "",
      kecamatan: "Baki Surakarta Jawa Tengah 57556",
      alamat: "Jl. Raya Songgolangit No. 28 RT 01 / RW 06 Kel. Gentan Kec. Baki Surakarta Jawa Tengah  57556",
      kodePos: "57556",
    },
  },
  {
    zone: "Central Java",
    region: "Java 2",
    area: "Surakarta",
    subArea: "Surakarta",
    pic1: { name: "ADITYA DENNY OENTORO", email: "adityadenny.oentoro@panamas.com", phone: "08112773234" },
    pic2: { name: "Krahayoni Yonit", email: "Yonit.Krahayoni@contracted.sampoerna.com", phone: "085725003322" },
    remarks: "PIC 1 ARA PIC 2 Logistik",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Tengah",
      kotaKabupaten: "",
      kecamatan: "Baki Surakarta Jawa Tengah 57556",
      alamat: "Jl. Raya Songgolangit No. 28 RT 01 / RW 06 Kel. Gentan Kec. Baki Surakarta Jawa Tengah  57556",
      kodePos: "57556",
    },
  },
  {
    zone: "Central Java",
    region: "Java 2",
    area: "Yogyakarta",
    subArea: "Yogyakarta",
    pic1: { name: "NANANG HASIM", email: "nanang.hasim@panamas.com", phone: "081222552217" },
    pic2: { name: "Siswi Artiningsih", email: "siswi.artiningsih@contracted.sampoerna.com", phone: "081213954245" },
    remarks: "PIC 1 ARA PIC 2 Logistik",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Sleman",
      kecamatan: "Sleman",
      alamat: "Jl. Mulungan No 234, Sendangadi, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55285",
      kodePos: "55285",
    },
  },
  {
    zone: "Central Java",
    region: "Java 3",
    area: "Kediri",
    subArea: "Kediri",
    pic1: { name: "KHOERIYAH, ASROFIYATUL", email: "asrofiyatul.khoeriyah@panamas.com", phone: "08113777167" },
    pic2: { name: "Wahyu Adityansyah", email: "wahyu.adityansyah@panamas.com", phone: "08113004486" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Kediri",
      kecamatan: "Kota Kediri",
      alamat: "Jl. Supersemar No. 100 - 104, Kel. Ngronggo, Kec. Kota Kediri, Kediri-64127",
      kodePos: "64127",
    },
  },
  {
    zone: "Central Java",
    region: "Java 3",
    area: "Pati",
    subArea: "Pati",
    pic1: { name: "WIJANARKO, EDO", email: "edo.wijanarko@panamas.com", phone: "08970324007" },
    pic2: { name: "Iwanuddin", email: "iwan.iwanudin@panamas.com", phone: "08112999954" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Tengah",
      kotaKabupaten: "",
      kecamatan: "Pati",
      alamat: "Jl. Raya Pati - Tayu KM. 3, Desa Mulyoharjo, Kec. Pati, Provinsi Jawa Tengah 59151",
      kodePos: "59151",
    },
  },
  {
    zone: "Central Java",
    region: "Java 3",
    area: "Semarang",
    subArea: "Semarang",
    pic1: { name: "ZALDI ARDIANSYAH", email: "zaldi.ardiansyah@panamas.com", phone: "085740611746" },
    pic2: { name: "Aflach Hakiki", email: "MuhamadAflach.Hakiki@panamas.com", phone: "081379133495" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. Suriyadi No. 9 Kalicari Pedurungan Semarang",
      kodePos: "",
    },
  },
  {
    zone: "Central Java",
    region: "Java 3",
    area: "Tegal",
    subArea: "Tegal",
    pic1: { name: "RIZDINANTI, DARIN ALYA KHAIRUNNISA", email: "darinalyakhairunnisa.rizdinanti@panamas.com", phone: "087889627705" },
    pic2: { name: "Nicho Sudjana", email: "nicho.sudjana@panamas.com", phone: "08172839666" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. Raya Tegal Pemalang KM. 5 No. 48\nRT/RW 01/03\nKelurahan Padaharja Tegal, Kecamatan Kramat 52181",
      kodePos: "",
    },
  },
  {
    zone: "Central Java",
    region: "Java 3",
    area: "Tuban",
    subArea: "Tuban",
    pic1: { name: "FADEL, ONGKOWIDJOYO", email: "FadelMumtaaza.Ongkowidjoyo@panamas.com", phone: "082148474846" },
    pic2: { name: "Akbar Ibrahim Mubin", email: "AkbarIbrahim.Mubin@panamas.com", phone: "08117215075" },
    remarks: "",
    note: "Move to new office - KPS 41",
    shippingAddress: {
      provinsi: "Jawa Timur",
      kotaKabupaten: "",
      kecamatan: "Semanding Tuban - Jawa Timur",
      alamat: "Jl. Mastrip 1 No. 1 RT. 02 RW. 05  Kel. Karang Kec. Semanding Tuban - Jawa Timur",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 1",
    area: "Balikpapan",
    subArea: "Balikpapan",
    pic1: { name: "Syarifuddin", email: "syarifuddin.syarifuddin@panamas.com", phone: "08115030239" },
    pic2: { name: "Idzhar Bisri", email: "idzhar.bisri@panamas.com", phone: "085247429192" },
    remarks: "PIC 2 (Team HMS)",
    note: "",
    shippingAddress: {
      provinsi: "Bali",
      kotaKabupaten: "Balikpapan 76114 (Depan Telkom BDI)",
      kecamatan: "Balikpapan Selatan",
      alamat: "Jl MT Haryono, RT.26 No.199 Kel Sungai Nangka Kec. Balikpapan Selatan, Kota Balikpapan 76114 (Depan Telkom BDI)",
      kodePos: "76114",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 1",
    area: "Banjarmasin",
    subArea: "Banjarmasin",
    pic1: { name: "Desy Seventina Simanjuntak", email: "desyseventina.simanjuntak@panamas.com", phone: "081348491014" },
    pic2: { name: "Redy Setiawan", email: "redy.setiawan@sampoerna.com", phone: "085230353146" },
    remarks: "PIC 2  (Team Logistic)",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "BANJAR 70654 KALIMANTAN SELATAN",
      kecamatan: "",
      alamat: "JL. AHMAD YANI KM 10.4, KERTAK HANYAR, KABUPATEN BANJAR 70654 KALIMANTAN SELATAN",
      kodePos: "70654",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 1",
    area: "Banjarmasin",
    subArea: "DPC Barabai",
    pic1: { name: "Exzcozetha Pasca Pratama A", email: "exzcozethapascapratamaarya.aditya@panamas.com", phone: "08115734912" },
    pic2: { name: "Dicky Royanda", email: "dicky.royanda@sampoerna.com", phone: "082277099003" },
    remarks: "PIC 2  (Team Logistic)",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "JL. BRIGJEN H. HASAN BASERI RT 07 RW 01, BUKAT, BARABAI 71315 KALIMANTAN SELATAN",
      kodePos: "71315",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 1",
    area: "Banjarmasin",
    subArea: "EZD Kotabaru",
    pic1: { name: "Teguh Prasetyo", email: "teguh.prasetyo@panamas.com", phone: "0811425006" },
    pic2: { name: "Teguh Prasetyo", email: "teguh.prasetyo@panamas.com", phone: "0811425006" },
    remarks: "PIC 2  (Team HMS)",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "JL. H. HASAN BASRI KM 4, PULAU LAUT UTARA, KOTABARU KALIMANTAN SELATAN",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 1",
    area: "Berau",
    subArea: "Berau",
    pic1: { name: "Johan Calvindoro", email: "johan.calvindoro@panamas.com", phone: "08115553060" },
    pic2: { name: "Junior Maurion Robert", email: "maurion.junior@panamas.com", phone: "08114810234" },
    remarks: "PIC 2  (Team HMS)",
    note: "",
    shippingAddress: {
      provinsi: "Kalimantan Timur",
      kotaKabupaten: "Berau",
      kecamatan: "",
      alamat: "CV. Sinar Mas Jaya, Jl. S.A. Maulana No. 30, Tanjung Redeb, Kab. Berau, Kalimantan Timur, 77312",
      kodePos: "77312",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 1",
    area: "Berau",
    subArea: "Sales Point Nunukan",
    pic1: { name: "Acep Sudrajat", email: "acep.sudrajat@panamas.com", phone: "08114134888" },
    pic2: { name: "Lukman", email: "lukman.pim@yahoo.com", phone: "085348887695" },
    remarks: "PIC 2  (Team EZD)",
    note: "",
    shippingAddress: {
      provinsi: "Kalimantan Utara",
      kotaKabupaten: "",
      kecamatan: "Nunukan. Kalimantan Utara",
      alamat: "PT Primantara Indah Makmur, Jl TVRI RT 02 Depan Toko Bintang Mode, sebelah Toyota, Kel. Nunukan Timur, Kec. Nunukan. Kalimantan Utara",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 1",
    area: "Berau",
    subArea: "Sales Point Tanjung Redeb",
    pic1: { name: "Johan Calvindoro", email: "johan.calvindoro@panamas.com", phone: "08115553060" },
    pic2: { name: "Junior Maurion Robert", email: "maurion.junior@panamas.com", phone: "08114810234" },
    remarks: "PIC 2  (Team HMS)",
    note: "",
    shippingAddress: {
      provinsi: "Kalimantan Timur",
      kotaKabupaten: "Berau",
      kecamatan: "",
      alamat: "CV. Sinar Mas Jaya, Jl. S.A. Maulana No. 30, Tanjung Redeb, Kab. Berau, Kalimantan Timur, 77312",
      kodePos: "77312",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 1",
    area: "Berau",
    subArea: "Sales Point Tarakan",
    pic1: { name: "Acep Sudrajat", email: "acep.sudrajat@panamas.com", phone: "08114134888" },
    pic2: { name: "Alam", email: "alam.pim@outlook.com", phone: "081253674200" },
    remarks: "PIC 2  (Team EZD)",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "Tarakan Barat",
      alamat: "PT Primantara Indah Makmur, Jl Mulawarman No. 40 RT 27 Kel. Karang Anyar Pantai Kec. Tarakan Barat, Tarakan, Kaltara 77111",
      kodePos: "77111",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 1",
    area: "Samarinda",
    subArea: "DPC Sengatta",
    pic1: { name: "Hendra Wirawan", email: "hendra.wirawan@panamas.com", phone: "08125578887" },
    pic2: { name: "Endi Fahrudi", email: "endi.fahrudi@sampoerna.com", phone: "081347466949" },
    remarks: "PIC 2  (Team Logistic)",
    note: "",
    shippingAddress: {
      provinsi: "Kalimantan",
      kotaKabupaten: "",
      kecamatan: "Sangatta Utara Kutai Timur East Kalimantan 75611 Indonesia",
      alamat: "Jl. Yos Sudarso II Komp. Thomas Square D7 – 8; Desa. Sangatta Utara, Kec. Sangatta Utara Kutai Timur East Kalimantan 75611 Indonesia",
      kodePos: "75611",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 1",
    area: "Samarinda",
    subArea: "Samarinda",
    pic1: { name: "Irwansyah Irwan", email: "irwan.irwansyah@panamas.com", phone: "08115858399" },
    pic2: { name: "Yahjimu", email: "yahjimu.yahjimu@sampoerna.com", phone: "081333556003" },
    remarks: "PIC 2  (Team Logistic)",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Samarinda 75124",
      kecamatan: "Samarinda Ulu",
      alamat: "Jl. Kadrie Oening No. 169 RT. 18, Kel. Air Hitam, Kec. Samarinda Ulu, Kota Samarinda 75124",
      kodePos: "75124",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 2",
    area: "Palangkaraya",
    subArea: "EZD Pangkalan Bun",
    pic1: { name: "Ahmad Albar", email: "Albar.Albar@panamas.com", phone: "08116700599" },
    pic2: { name: "M Rasyid Rabbani", email: "m.rasyid.rabbani@panamas.com", phone: "081234311165" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "d/a: CV. BALI UTAMA\nJl. Pakunegara No. 60A, Kel. Baru, Kec. Arut Selatan, Pangkalan Bun, Kab. Kotawaringin Barat, 74113. (Belakang Dealer Yamaha Duta Indah)",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 2",
    area: "Palangkaraya",
    subArea: "EZD Sampit",
    pic1: { name: "Abraham Heret Asie", email: "Abraham.Asie@panamas.com", phone: "08115218081" },
    pic2: { name: "M Rasyid Rabbani", email: "m.rasyid.rabbani@panamas.com", phone: "081234311165" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "d/a : PT Putra Niaga Bersama\nJl. HM Arsyad km. 3.5 No.89, (sebelum bundaran KB/Samping Kantor Sawit PT Sinarmas) Kota Sampit, Kec. MB Ketapang, Kab. Kotawaringin Timur - 74325",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 2",
    area: "Palangkaraya",
    subArea: "Palangkaraya",
    pic1: { name: "Dicky Hariyanto Yudha Tarigan", email: "Dicky.Tarigan@panamas.com", phone: "08114503279" },
    pic2: { name: "M Rasyid Rabbani", email: "m.rasyid.rabbani@panamas.com", phone: "081234311165" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "PT HM SAMPOERNA, d/a: CV. BETANG MAS\nJl. Nyai Undang No. 17, Kel. Langkai, Kec. Pahandut, Kota Palangkaraya, 73111",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 2",
    area: "Pontianak",
    subArea: "EZD Ketapang",
    pic1: { name: "PUSDIKA DEVRIES", email: "Pusdika.Devries@panamas.com", phone: "08114101399" },
    pic2: { name: "ICHWAN", email: "Ichwan.Ichwan1@sampoerna.com", phone: "08114449492" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "PT  HM SAMPOERNA TBK, \nd/a: PT. SETIA PAWAN JAYA\nJL AYANI NO 100A, KEC DELTA PAWAN KETAPANG, UP SURIYANTO/MARGUS FINA/TENGKU HARDIANSAH",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 2",
    area: "Pontianak",
    subArea: "Pontianak",
    pic1: { name: "Kiki Perjaman", email: "kiki.perjaman@panamas.com", phone: "08115738705" },
    pic2: { name: "ICHWAN", email: "Ichwan.Ichwan1@sampoerna.com", phone: "08114449492" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Kalimantan Barat",
      kotaKabupaten: "Kubu Raya",
      kecamatan: "Sungai Raya",
      alamat: "PT HM SAMPOERNA AREA PONTIANAK, Pergudangan Ocean 88 Blok 8J, No 01-06, Jalan Adi Sucipto KM 10.5, Kelurahan Sungai Raya, Kecamatan Sungai Raya, Kabupaten Kubu Raya, Provinsi Kalimantan Barat, POS 78391",
      kodePos: "78391",
    },
  },
  {
    zone: "East",
    region: "Kalimantan 2",
    area: "Sintang",
    subArea: "Sintang",
    pic1: { name: "Mikhael Elsafan", email: "MIKHAELELSAFAN.SETIAWAN@PANAMAS.COM", phone: "081393065777" },
    pic2: { name: "SUPRIYONO", email: "supriyono.supriyono1@contracted.sampoerna.com", phone: "085348742901" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Kalimantan Barat",
      kotaKabupaten: "Sintang Sintang Kalimantan Barat 78651",
      kecamatan: "Sungai Tebelian Kab. Sintang Sintang Kalimantan Barat 78651",
      alamat: "PT HM SAMPOERNA AREA SINTANG Desa Balai Agung; Jalan Sintang – Pontianak Dusun Nenak RT 003 / RW 001 Kec. Sungai Tebelian Kab. Sintang Sintang  Kalimantan Barat  78651",
      kodePos: "78651",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 1",
    area: "Kendari",
    subArea: "EZD Bau-Bau",
    pic1: { name: "Adi Wicaksono", email: "adi.wicaksono@panamas.com", phone: "08113344112" },
    pic2: { name: "Herry Widianto", email: "herry.widianto@panamas.com", phone: "0811524034" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Sulawesi Tenggara",
      kotaKabupaten: "Baubau",
      kecamatan: "",
      alamat: "CV SARAN MAJU BERSAMA. Jalan Budi Utomo No 17 Wangkanapi. Wolio, Kota Baubau, Sulawesi Tenggara. Telfon: 0402-2822019",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 1",
    area: "Kendari",
    subArea: "Kendari",
    pic1: { name: "Herry Widianto", email: "herry.widianto@panamas.com", phone: "0811524034" },
    pic2: { name: "Ibrahim Tualeka", email: "ibrahim.tualeka@panamas.com", phone: "08113613432" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Sulawesi Tenggara",
      kotaKabupaten: "Kendari",
      kecamatan: "",
      alamat: "PT. HM. Sampoerna, Tbk, JL. Made Sabara II No. 1; Kel.Korumba,Kec.Madonga, Kota Kendari, Sulawesi Tenggara, Kode Pos : 93111, Indonesia",
      kodePos: "93111",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 1",
    area: "Makassar 1",
    subArea: "Makassar 1",
    pic1: { name: "Cisilia Geby Sapari", email: "cisilia.gebysapari@sampoerna.com", phone: "081944414907" },
    pic2: { name: "Arin Setianingtyas", email: "arin.setianingtyas@sampoerna.com", phone: "081226506150" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Sulawesi Selatan",
      kotaKabupaten: "Makassar",
      kecamatan: "Tamalanrea",
      alamat: "PT.HM.Sampoerna, Tbk, Jl. Prof. Dr. Ir. Sutami No. 4; Kel. Parangloe, Kec. Tamalanrea, Kota Makassar, Sulawesi Selatan, Kode Pos : 90244, Indonesia",
      kodePos: "90244",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 1",
    area: "Makassar 2",
    subArea: "Makassar 2",
    pic1: { name: "Afriyandi Ramadhan Naim", email: "afriyandiramadhan.naim@sampoerna.com", phone: "082194371731" },
    pic2: { name: "Harry Tobo", email: "Harry.Tobo@sampoerna.com", phone: "085145222108" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Sulawesi Selatan",
      kotaKabupaten: "Bone",
      kecamatan: "Palakka",
      alamat: "PT. HM. Sampoerna, Tbk, Jl. Poros Bone - Makassar KM. 7 Dusun Bakae Desa Passipo, Kec. Palakka, Kabupaten Bone, Sulawesi Selatan, Kode Pos: 92761, Indonesia.",
      kodePos: "92761",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 1",
    area: "Palu",
    subArea: "EZD Luwuk",
    pic1: { name: "Wilibrordus Dhaneswara", email: "Wilibrordus.Dhaneswara@sampoerna.com", phone: "08112611349" },
    pic2: { name: "Rocky", email: "RockyAndaya.Aris@sampoerna.com", phone: "08115909909" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Luwuk Banggai",
      kecamatan: "Nambo",
      alamat: "Jl. Trans Luwuk Batui, Kel. Koyoan, KM. 15, Kompleks Pergudangan Luwuk (TOTALINDO), Kel. Koyoan, Kec. Nambo, Kab. Luwuk Banggai, SulTeng 94711",
      kodePos: "94711",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 1",
    area: "Palu",
    subArea: "Palu",
    pic1: { name: "Lompo Tabrani", email: "lompo.tabrani@sampoerna.com", phone: "0811453499" },
    pic2: { name: "Alfiyanto Pontoh", email: "alfiyanto.pontoh@sampoerna.com", phone: "082271776655" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Sulawesi Tengah",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. Soekarno Hatta no. 88 (Gudang Coklat PT. SCC), Tondo, Mantikulore, Sulawesi Tengah. Kode Pos. 94111",
      kodePos: "94111",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 1",
    area: "Pare-Pare",
    subArea: "DPC Palopo",
    pic1: { name: "Ronald Kakiay", email: "Ronald.Kakiay@sampoerna.com", phone: "0811404234" },
    pic2: { name: "Dian Eka Putri", email: "Dian.EkaPutri@sampoerna.com", phone: "085342549483" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Palopo 91926",
      kecamatan: "Wara Selatan Kota Palopo 91926",
      alamat: "PT HM Sampoerna Jl Jend Sudirman Km 3 Rt 3 Kel Binturu Kec Wara Selatan Kota Palopo 91926",
      kodePos: "91926",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 1",
    area: "Pare-Pare",
    subArea: "Pare-Pare",
    pic1: { name: "Sutriana Basri", email: "sutriana.basri@panamas.com", phone: "085241988149" },
    pic2: { name: "Rafiuddin", email: "rafiuddin.rafiuddin@panamas.com", phone: "081355003207" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Pare Pare Sulsel",
      kecamatan: "Ujung Kota Pare Pare Sulsel",
      alamat: "PT HM Sampoerna TBK, Jl. Jend. Ahmad Yani Km. 6 Blok. C kel. Lapadde Kec. Ujung Kota Pare Pare Sulsel",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Ambon",
    subArea: "Ambon",
    pic1: { name: "Muhamad Mulfi Latuconsina", email: "mulfi.latuconsina@sampoerna.com", phone: "0811478900" },
    pic2: { name: "Jossy Muskitta", email: "Jossy.Muskitta@sampoerna.com", phone: "082239111234" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Maluku",
      kotaKabupaten: "Ambon",
      kecamatan: "",
      alamat: "Jl. Laksda Leo Wattimena 50, Nania, Baguala, Kota Ambon, Maluku",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Ambon",
    subArea: "EZD Tual",
    pic1: { name: "Tualeka Ibrahim", email: "ibrahim.tualeka@sampoerna.com", phone: "08113613432" },
    pic2: { name: "Jossy Muskitta", email: "Jossy.Muskitta@sampoerna.com", phone: "082239111234" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Maluku",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. Abdurahman Wahid (Poros Bandara). Kei kecil, Desa Faan, Maluku Tenggara",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Gorontalo",
    subArea: "Gorontalo",
    pic1: { name: "Firmansyah", email: "FIRMAN.FIRMANSYAH@PANAMAS.COM", phone: "082191960830" },
    pic2: { name: "Mohamad Yaasin", email: "Mohamad.Yaasin@sampoerna.com", phone: "08114345105" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Gorontalo",
      kotaKabupaten: "Gorontalo",
      kecamatan: "Sipatana Kota Gorontalo",
      alamat: "Jl. John Aryo Katili No. 37 Kel. Tanggikiki, Kec. Sipatana Kota Gorontalo",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Jayapura",
    subArea: "EZD Biak",
    pic1: { name: "Amiruddin", email: "amiruddin.amiruddin@sampoerna.com", phone: "08124750522" },
    pic2: { name: "Debby", email: "cv.irianrayaperkasa@gmail.com", phone: "082362535495" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "CV. Irian Raya\nBpk. Amiruddin (PT. HM Sampoerna, Tbk) /Debby\nJl. Bosnik Raya No 2. Biak– Papua\nPhone : (0981) 27035; 08124750522/082362535495",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Jayapura",
    subArea: "EZD Merauke",
    pic1: { name: "Miftakul Huda", email: "Miftakul.Huda@Sampoerna.com", phone: "08114856787" },
    pic2: { name: "Sukri Sukur", email: "admcomp.merauke@gmail.com", phone: "085244907773" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "CV. Hanjaya Capital \nUp. Bpk. Miftakhul Huda (PT. HM Sampoerna, Tbk) / Bpk Sriyanto\nJl. Poros Tujuh Wali-wali ( sebelum jembatan Maro )\nKel Kamundu Kec. Merauke\nMerauke - Papua 99607\nPhone : (0971) 322143; 08114856787; 08114906080",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Jayapura",
    subArea: "EZD Nabire",
    pic1: { name: "Devy Marlissa", email: "Devy.Marlissa@sampoerna.com", phone: "08114321236" },
    pic2: { name: "Asmawati Abdullah", email: "asmawatiabdullah43@gmail.com", phone: "08114809619" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Papua",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "CV. Mandala Papua ; Jl Merdeka (Samping toko Javaco) Nabire, Prov. Papua - Indonesia, 98816",
      kodePos: "98816",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Jayapura",
    subArea: "EZD Serui",
    pic1: { name: "Amiruddin", email: "amiruddin.amiruddin@sampoerna.com", phone: "08124750522" },
    pic2: { name: "Debby", email: "cv.irianrayaperkasa@gmail.com", phone: "082362535495" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Papua",
      kotaKabupaten: "Kepulauan Yapen - kota Serui - Papua Kode Pos 98211",
      kecamatan: "Anotaurei",
      alamat: "JL. Frans Kaisepo, RT02, RW03, Kampung Warari, Kecamatan Anotaurei, Kab. Kepulauan Yapen - kota Serui - Papua Kode Pos 98211",
      kodePos: "98211",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Jayapura",
    subArea: "Jayapura",
    pic1: { name: "Wawan Kurniawan", email: "wawan.kurniawan1@sampoerna.com", phone: "0811444786" },
    pic2: { name: "Rahawarin Germanus", email: "germanus.rahawarin@contracted.sampoerna.com", phone: "081289315014" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "PT HM Sampoerna Tbk., (Up. Wawan Kurniawan/Gerto) Jl. Raya Kelapa Dua Entrop (seberang Ruko Triple L Gedung Kuning 3 Lt), Jayapura Selatan 99221 JAYAPURA INDONESIA Phone : 0811444786/081289315014",
      kodePos: "99221",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Manado",
    subArea: "Manado",
    pic1: { name: "Anastasia Pricilia Sipasulta", email: "AnastasiaPricilia.Sipasulta@panamas.com", phone: "081247049049" },
    pic2: { name: "Sutrisno Slamet", email: "Sutrisno.Slamet@Sampoerna.com", phone: "081244024234" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Sulawesi Utara",
      kotaKabupaten: "",
      kecamatan: "Tikala",
      alamat: "Jl. Pingkan Matindas No.57C (Kompleks Multifood), Kel. Dendengan Dalam, Kec Tikala, Manado, Sulawesi Utara 95127",
      kodePos: "95127",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Sorong",
    subArea: "Sales Point Fak-Fak",
    pic1: { name: "Wawan Setiawan", email: "Wawan.Setiawan@sampoerna.com", phone: "0811512340" },
    pic2: { name: "wawan Setiawan", email: "Wawan.Setiawan@sampoerna.com", phone: "0811512340" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "TOKO DEWATA FAK FAK \nUp . Yetti 08114892212\nJl. Gajah Mada No. 5 Kel. Fak Fak Utara. Fak Fak \nPapua Barat.",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Sorong",
    subArea: "Sales Point Kaimana",
    pic1: { name: "Wawan Setiawan", email: "Wawan.Setiawan@sampoerna.com", phone: "0811512340" },
    pic2: { name: "wawan Setiawan", email: "Wawan.Setiawan@sampoerna.com", phone: "0811512340" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Papua",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "TOKO AMARISA KAIMANA Jl. Trikora RT.003/RW.000 Kaimana Papua Barat",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Sorong",
    subArea: "Sales Point Manokwari",
    pic1: { name: "Leonardo Samosir", email: "leonardo.samosir@sampoerna.com", phone: "08124021402" },
    pic2: { name: "Leonardo Samosir", email: "leonardo.samosir@sampoerna.com", phone: "08124021402" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Papua",
      kotaKabupaten: "Manokwari Papua Barat",
      kecamatan: "",
      alamat: "CV. Pelita Abadi Jl. Angkasa Mulyono Reremi Puncak Deretan Senyum 5000 Kel. Amban Distrik Manokwari Barat Kab. Manokwari Papua Barat",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Sorong",
    subArea: "Sales Point Timika",
    pic1: { name: "Jafar Ode", email: "Jafar.Ode@sampoerna.com", phone: "0811471576" },
    pic2: { name: "Jafar Ode", email: "Jafar.Ode@sampoerna.com", phone: "0811471576" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Papua",
      kotaKabupaten: "Mimika – Papua",
      kecamatan: "",
      alamat: "UD. Sejahtera Mandiri  Jl. Rambutan Jalur 2 Pabrik Pecah Batu Kel. Timika Jaya, Distrik Mimika Baru Kabupaten Mimika – Papua, Phone : 08114810234",
      kodePos: "",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Sorong",
    subArea: "Sorong",
    pic1: { name: "Wawan Setiawan", email: "Wawan.Setiawan@sampoerna.com", phone: "0811512340" },
    pic2: { name: "wawan Setiawan", email: "Wawan.Setiawan@sampoerna.com", phone: "0811512340" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Papua",
      kotaKabupaten: "",
      kecamatan: "Sorong Timur - Papua Barat 98415",
      alamat: "UD. Sinar Mas Jl. Frans Kaiseipo Belakang SMEA KM 8 Kel. Malaingkedi Kecamatan Sorong Timur  - Papua Barat 98415",
      kodePos: "98415",
    },
  },
  {
    zone: "East",
    region: "Sulawesi 2",
    area: "Ternate",
    subArea: "Ternate",
    pic1: { name: "Rizqi Hadi Putra", email: "rizqi.HadiPutra@panamas.com", phone: "'08114345555" },
    pic2: { name: "Emba, Riyadi", email: "Riyadi.Emba@sampoerna.com", phone: "082189524292" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Maluku",
      kotaKabupaten: "Ternate",
      kecamatan: "Ternate Selatan",
      alamat: "Jl. Raya Jati Besar No. 9 Kelurahan Ubo - Ubo, Kecamatan Ternate Selatan, Kota Ternate, Maluku Utara, Kode Pos 97717",
      kodePos: "97717",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Denpasar",
    subArea: "Denpasar",
    pic1: { name: "Aria Anugrah Mulia", email: "AriaAnugrah.Mulia@panamas.com", phone: "081224602527" },
    pic2: { name: "I Made Eriana Jayadi", email: "IMadeEriana.Jayadi@contracted.sampoerna.com", phone: "081338567965" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "KANTOR HM SAMPOERNA JL. BY PASS NGURAH RAI NO. 88X SUWUNG KAUH, PEMOGAN, DENPASAR SELATAN, DENPASAR, BALI",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Denpasar",
    subArea: "DPC Singaraja",
    pic1: { name: "Paus Peterson Tehang", email: "PausPeterson.Tehang@sampoerna.com", phone: "085725722777" },
    pic2: { name: "Gede Suwika", email: "Gede.Suwika@contracted.sampoerna.com", phone: "081805303883" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "JL NGURAH RAI NO 9, BULELENG, BALI, INDONESIA 81117",
      kodePos: "81117",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Kupang",
    subArea: "DPC Ende",
    pic1: { name: "Dandy K. Herlambang", email: "DandyK.Herlambang@panamas.com", phone: "081330915116" },
    pic2: { name: "Clara Kekado", email: "Clara.Kekado@contracted.sampoerna.com", phone: "081315442109" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Nusa Tenggara Timur",
      kotaKabupaten: "",
      kecamatan: "NDONA",
      alamat: "JL FLORES RT 003/RW 002, DESA NANGANESA, KEC NDONA, ENDE - NTT 86361",
      kodePos: "86361",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Kupang",
    subArea: "DPC Ruteng",
    pic1: { name: "Arky Perawin", email: "JohanesBaptistaAreyAriesta.Perawin@panamas.com", phone: "085237374174" },
    pic2: { name: "Rikardo Pape", email: "Rikardo.Pape@contracted.sampoerna.com", phone: "081237454418" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Nusa Tenggara Timur",
      kotaKabupaten: "Manggarai - NTT 86115",
      kecamatan: "",
      alamat: "Jl. Glodia Selatan, Pauh Ruteng - Kab. Manggarai - NTT 86115",
      kodePos: "86115",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Kupang",
    subArea: "EZD Alor",
    pic1: { name: "Hanif Rusdiono", email: "HanifArif.Rusdiono@sampoerna.com", phone: "081802009234" },
    pic2: { name: "Ruth Handaya", email: "Ruth.Handaya@contracted.sampoerna.com", phone: "082145289594" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jln. Otto Iskandardinata RT 004/RW 002, Desa Motongbang,\nKecamatan Teluk Mutiara, Kabupaten Alor Kalabahi NTT",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Kupang",
    subArea: "EZD Atambua",
    pic1: { name: "Hanif Rusdiono", email: "HanifArif.Rusdiono@sampoerna.com", phone: "081802009234" },
    pic2: { name: "Ruth Handaya", email: "Ruth.Handaya@contracted.sampoerna.com", phone: "082145289594" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Nusa Tenggara Timur",
      kotaKabupaten: "BELU - NTT",
      kecamatan: "ATAMBUA BARAT - KABUPATEN BELU - NTT",
      alamat: "JL. GAJAHMADA, KEL. TULAMALAE, KEC. ATAMBUA BARAT - KABUPATEN BELU - NTT",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Kupang",
    subArea: "EZD Maumere",
    pic1: { name: "Teddy Nanang Siswanto", email: "TeddyNanang.Siswanto@panamas.com", phone: "081339939234" },
    pic2: { name: "Clara Kekado", email: "Clara.Kekado@contracted.sampoerna.com", phone: "081315442109" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Nusa Tenggara Timur",
      kotaKabupaten: "SIKKA - NTT",
      kecamatan: "",
      alamat: "JL. GAJAH MADA NO. 234 - KEL.MADAWAT - KEC.ALOK - KABUPATEN SIKKA - NTT",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Kupang",
    subArea: "EZD Sumba",
    pic1: { name: "Mahdum Khalimi", email: "Mahdum.Khalimi@panamas.com", phone: "08123755933" },
    pic2: { name: "Ruth Handaya", email: "Ruth.Handaya@contracted.sampoerna.com", phone: "082145289594" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Nusa Tenggara Timur",
      kotaKabupaten: "SUMBA TIMUR - NTT",
      kecamatan: "",
      alamat: "JL. MATAWAI AMAHU NO 234 WAINGAPU - KABUPATEN SUMBA TIMUR - NTT",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Kupang",
    subArea: "Kupang",
    pic1: { name: "Vina Yanuarica", email: "Vina.Yanuarica@panamas.com", phone: "08113811031" },
    pic2: { name: "Ruth Handaya", email: "Ruth.Handaya@contracted.sampoerna.com", phone: "082145289594" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Nusa Tenggara Timur",
      kotaKabupaten: "",
      kecamatan: "KELAPA LIMA. KUPANG - NTT",
      alamat: "JLN. S.K LERRICK RT 010 RW 005, KEC. KELAPA LIMA. KUPANG - NTT",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Mataram",
    subArea: "EZD Sumbawa - Bima",
    pic1: { name: "Gde Adhy Wirawan", email: "GdeAdhy.Wirawan@panamas.com", phone: "+62 878-6430-0355" },
    pic2: { name: "Fahmi", email: "Muhammad.Hannan@contracted.sampoerna.com", phone: "+62 823-3945-7157" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Nusa Tenggara Barat",
      kotaKabupaten: "BIMA NTB",
      kecamatan: "RASANA’E BARAT KOTA BIMA NTB",
      alamat: "PT CDU BIMA, JL. ST. KAHARUDIN NO. 01 KEL. DARA KEC. RASANA’E BARAT KOTA  BIMA NTB",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Mataram",
    subArea: "EZD Sumbawa - Sumbawa",
    pic1: { name: "I Gusti Ketut Agung Bayusena", email: "Bayu.Bayusena@panamas.com", phone: "+62 811-3822-340" },
    pic2: { name: "Fahmi", email: "Muhammad.Hannan@contracted.sampoerna.com", phone: "+62 823-3945-7157" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "Nusa Tenggara Barat",
      kotaKabupaten: "SUMBAWA BESAR NTB",
      kecamatan: "",
      alamat: "PT CDU SUMBAWA , JL HIJRAH NO. 234 PANTO DAENG, KELURAHAN BRANG BARA, KEC.SUMBAWA,KAB. SUMBAWA BESAR NTB",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Bali NT",
    area: "Mataram",
    subArea: "Mataram",
    pic1: { name: "Muchlisa", email: "lisa.muchlisa@sampoerna.com", phone: "082349541175" },
    pic2: { name: "Fahmi", email: "Muhammad.Hannan@contracted.sampoerna.com", phone: "+62 823-3945-7157" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "SANDUBAYA. MATARAM. 83232",
      alamat: "JLN.TGH SALEH HAMBALI NO 234. DASAN CERMEN, KEC. SANDUBAYA. MATARAM. 83232",
      kodePos: "83232",
    },
  },
  {
    zone: "East Java",
    region: "Java 4",
    area: "Gresik",
    subArea: "Gresik",
    pic1: { name: "Hidayatullah, Miftah Farid", email: "MiftahFarid.Hidayatullah@panamas.com", phone: "08113142287" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "KAWASAN INDUSTRI MASPION 2, JL. BETA KAV 3 - 6, MANYAR, GRESIK",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Java 4",
    area: "Jember",
    subArea: "DPC Banyuwangi",
    pic1: { name: "Yudianto, Deny", email: "Deny.Yudianto@panamas.com", phone: "08113372855" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "BANYUWANGI",
      kecamatan: "ROGOJAMPI",
      alamat: "DUSUN JAJANGSURAT RT. 001 RW. 001, DESA KARANGBENDO, KEC ROGOJAMPI, KABUPATEN BANYUWANGI",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Java 4",
    area: "Jember",
    subArea: "Jember",
    pic1: { name: "Yudianto, Deny", email: "Deny.Yudianto@panamas.com", phone: "08113372855" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "JEMBER",
      kecamatan: "AJUNG",
      alamat: "JL. WOLTER MONGINSIDI NO.884, KEC. AJUNG, KAB. JEMBER",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Java 4",
    area: "Malang",
    subArea: "Malang",
    pic1: { name: "Paramita, Cok Laksmi Pradna", email: "CokLaksmiPradna.Paramita@panamas.com", phone: "08111091092" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "MALANG",
      kecamatan: "BLIMBING",
      alamat: "JL.S PARMAN 44 MALANG, KEC BLIMBING, KOTA MALANG",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Java 4",
    area: "Mojokerto",
    subArea: "Mojokerto",
    pic1: { name: "Purwanto, Agus (Sales)", email: "Agus.Purwanto@panamas.com", phone: "081232882780" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "TROWULAN",
      alamat: "JL RAYA MOJOKERTO - MOJOAGUNG NO.122; DESA WATES UMPAK, KEC. TROWULAN, EAST JAVA 61362, MOJOKERTO INDONESIA",
      kodePos: "61362",
    },
  },
  {
    zone: "East Java",
    region: "Java 4",
    area: "Pamekasan",
    subArea: "Pamekasan",
    pic1: { name: "Al-Mukarromah, Mecca Paradise", email: "meccaparadise.al-mukarromah@panamas.com", phone: "08113000349" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "PAMEKASAN",
      kecamatan: "",
      alamat: "JL. RAYA SUMENEP NO.234, RENGOH, TAMBUNG, PADEMAWU, KABUPATEN PAMEKASAN, JAWA TIMUR 69323",
      kodePos: "69323",
    },
  },
  {
    zone: "East Java",
    region: "Java 4",
    area: "Probolinggo",
    subArea: "Probolinggo",
    pic1: { name: "Septiani, Lia", email: "Lia.Septiani@panamas.com", phone: "081133378999" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "KADEMANGAN",
      alamat: "JL. BRANTAS NO. 46, RT 03 / RW 04; KEL. PILANG, KEC. KADEMANGAN, 67221 PROBOLINGGO; +62335436209;EXT=86237109",
      kodePos: "67221",
    },
  },
  {
    zone: "East Java",
    region: "Java 4",
    area: "Sidoarjo",
    subArea: "Sidoarjo",
    pic1: { name: "Arum, Tri Sari", email: "TriSari.Arum@sampoerna.com", phone: "085648317707" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "JL BERBEK INDUSTRI VII NO 16-18 WARU SIDOARJO",
      kodePos: "",
    },
  },
  {
    zone: "East Java",
    region: "Java 4",
    area: "Surabaya",
    subArea: "Surabaya",
    pic1: { name: "Naila, Fania Eva", email: "FaniaEva.Naila@panamas.com", phone: "081288121483" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "JL BERBEK INDUSTRI VII NO 16-18 WARU SIDOARJO",
      kodePos: "",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Inner",
    area: "Depok",
    subArea: "Depok",
    pic1: { name: "Ferdi ferdiansyah", email: "Ferdiferdiansyah.Ferdiferdiansyah@Panamas.com", phone: "081381730984" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "ARA DEPOK",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Barat",
      kotaKabupaten: "Depok",
      kecamatan: "Sukmajaya",
      alamat: "Pesona view sentra bisnis Depok jalan Ir .H.juanda gedung A 11 lantai 1 kel.mekar jaya ,kec.sukma jaya Depok 16411, Jl. Ir H. Juanda, Mekar Jaya, Kec. Sukmajaya, Kota Depok, Jawa Barat 16411",
      kodePos: "16411",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Inner",
    area: "Jakarta Barat",
    subArea: "Jakarta Barat",
    pic1: { name: "Muhammad Luthfi Sobana", email: "MuhammadLuthfi.Sobana@Panamas.com", phone: "081290317020" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "ARA JKB",
    note: "",
    shippingAddress: {
      provinsi: "Jakarta",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. Panjang no.3 RT.11/RW.10, kebon jeruk, Jakarta Barat 11530",
      kodePos: "11530",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Inner",
    area: "Jakarta Pusat",
    subArea: "Jakarta Pusat",
    pic1: { name: "Nisa Ulfarida", email: "Nisa.Ulfarida@Panamas.com", phone: "085790201353" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "ARA JKP",
    note: "",
    shippingAddress: {
      provinsi: "Jakarta",
      kotaKabupaten: "Jakarta Pusat",
      kecamatan: "Kemayoran",
      alamat: "Jl. Garuda No.48, RW.5, Kemayoran, Kec. Kemayoran, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10620",
      kodePos: "10620",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Inner",
    area: "Jakarta Selatan",
    subArea: "Jakarta Selatan",
    pic1: { name: "R, Emir Hussein", email: "EmirHussein.R@panamas.com", phone: "085694080470" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "ARA JKS",
    note: "",
    shippingAddress: {
      provinsi: "Jakarta",
      kotaKabupaten: "Jakarta Selatan",
      kecamatan: "Ps. Minggu",
      alamat: "Jl. Raya Pasar Minggu No.60, RT.11/RW.5, Pejaten Tim., Kec. Ps. Minggu, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12510",
      kodePos: "12510",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Inner",
    area: "Jakarta Selatan",
    subArea: "Pondok Pinang JAKSEL",
    pic1: { name: "R, Emir Hussein", email: "EmirHussein.R@panamas.com", phone: "085694080470" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "ARA JKS",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Graha Pondok Pinang, Jalan Raharja No.1 RT.05/RW08 kel. Pondok Pinang, Kec, Pondok Pinang KEB-LAMA JAKSEL, Kode Pos 12310",
      kodePos: "12310",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Inner",
    area: "Jakarta Timur",
    subArea: "Jakarta Timur",
    pic1: { name: "Karina Numa Salsabila", email: "KarinaNuma.Salsabila@Panamas.com", phone: "087877835199" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "ARA JKT",
    note: "",
    shippingAddress: {
      provinsi: "Jakarta",
      kotaKabupaten: "Jakarta Timur DKI Jakarta 13930",
      kecamatan: "",
      alamat: "Jl. Raya Bekasi KM 18 No.9 RT 001/RW 004 Kel. Jatinegara Kec, Cakung Kota Jakarta Timur DKI Jakarta 13930",
      kodePos: "13930",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Inner",
    area: "Jakarta Timur",
    subArea: "Pasar Minggu",
    pic1: { name: "", email: "", phone: "" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "",
      kodePos: "",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Inner",
    area: "Jakarta Utara",
    subArea: "Jakarta Utara",
    pic1: { name: "Arie Khuwarizmi", email: "Arie.Khuwarizmi@Panamas.com", phone: "08119966644" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "ARA JKU",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. Plumpang Raya No.36 RT.07 RW.02; Kel.Tugu Selatan, Kec.Koja 14260",
      kodePos: "14260",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Outer",
    area: "Bekasi",
    subArea: "Bekasi",
    pic1: { name: "Laksana Aditya", email: "Aditya.Laksana@Panamas.com", phone: "089652086485" },
    pic2: { name: "Achmad Sufani", email: "achmad.sufani@contracted.sampoerna.com", phone: "081534744883" },
    remarks: "ARA BEKASI",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Bekasi 17510 (depan PT Citra Galvanizing Indonesia) 17510",
      kecamatan: "Tambun Selatan",
      alamat: "Jalan Setia Darma 2 RT/RW 004/003 No 108 Kelurahan Setiadarma, Kecamatan Tambun Selatan, Kabupaten Bekasi 17510 (depan PT Citra Galvanizing Indonesia) 17510",
      kodePos: "17510",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Outer",
    area: "Bogor",
    subArea: "Bogor",
    pic1: { name: "Nuril Hudhayani", email: "Nuril.Hudhayani@Panamas.com", phone: "08111993424" },
    pic2: { name: "Dede Ruswandi", email: "DEDE.RUSWANDI@contracted.sampoerna.com", phone: "0856-9476-3107" },
    remarks: "ARA BOGOR",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. Olimpic Raya Sentul Kavling B.10; Desa Sentul Kec Babakan Madang Kab Bogor\nBogor  West Java  16810",
      kodePos: "",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Outer",
    area: "Bogor",
    subArea: "Satelit Ciampea",
    pic1: { name: "Nuril Hudhayani", email: "Nuril.Hudhayani@Panamas.com", phone: "08111993424" },
    pic2: { name: "Aditya", email: "Aditya.Aditya@contracted.sampoerna.com", phone: "+62 812-3420-1993" },
    remarks: "ARA BOGOR",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Barat",
      kotaKabupaten: "Bogor",
      kecamatan: "Ciampea",
      alamat: "Jl. WR Borong No 29 RT 003/002, Desa Bojongrangkas, Kecamatan Ciampea, Kabupaten Bogor, Propinsi Jawa Barat 16620",
      kodePos: "16620",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Outer",
    area: "Karawang",
    subArea: "Karawang",
    pic1: { name: "Muhammad Taufik", email: "Muhammad.Taufik1@Panamas.com", phone: "085697297542" },
    pic2: { name: "Marlina", email: "Marlina.Marlina@contracted.sampoerna.com", phone: "085624789334" },
    remarks: "ARA KARAWANG",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "Karawang Timur 41314",
      alamat: "Jl. Alternatif Tanjungpura – Klari KM 3; Kel. Palumbonsari Kec. Karawang Timur 41314",
      kodePos: "41314",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Outer",
    area: "Rangkasbitung",
    subArea: "Rangkasbitung",
    pic1: { name: "Rohmat Martiadi", email: "Rohmat.Martiadi@Panamas.com", phone: "08111250109" },
    pic2: { name: "Ramin", email: "RAMIN.RAMIN@contracted.sampoerna.com", phone: "0815-1791-5054" },
    remarks: "ARA RANGKAS",
    note: "",
    shippingAddress: {
      provinsi: "Jakarta",
      kotaKabupaten: "",
      kecamatan: "Cipocok Jaya",
      alamat: "Jl. Raya Jakarta KM.4 Pakupatan Kp. Sapiah; RT.002/013, Kel. Penancangan, Kec. Cipocok Jaya, Serang, Banten , 42124 Indonesia",
      kodePos: "42124",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Outer",
    area: "Serang",
    subArea: "Serang",
    pic1: { name: "Mandala Prahasta", email: "RdMandalaIndra.Prahasta@panamas.com", phone: "081283208355" },
    pic2: { name: "Sudian Aditya", email: "Aditya.Sudian@contracted.sampoerna.com", phone: "085811460486" },
    remarks: "ARA SERANG",
    note: "",
    shippingAddress: {
      provinsi: "Banten",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. Soekarno Hatta (Bypass) No. 234, RT/RW 02/04; Kp. Baturambang, ds Cibadak, Kec.Cibadak, Lebak, Banten 42317",
      kodePos: "42317",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Outer",
    area: "Tangerang",
    subArea: "Satelit Cikupa",
    pic1: { name: "Julia Ratih Nur Indahsari", email: "JuliaRatihNur.Indahsari@Panamas.com", phone: "085750687605" },
    pic2: { name: "Deni Mulyana", email: "Deni.Mulyana@contracted.sampoerna.com", phone: "085779177958" },
    remarks: "ARA TANGERANG",
    note: "",
    shippingAddress: {
      provinsi: "Banten",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Kantor HM SAMPOERNA Jl. Raya Serang Km.19,2 Rt.15/06, Bojong, Cikupa, Tangerang, Banten 15710",
      kodePos: "15710",
    },
  },
  {
    zone: "Jakarta",
    region: "Jakarta Outer",
    area: "Tangerang",
    subArea: "Tangerang",
    pic1: { name: "Julia Ratih Nur Indahsari", email: "JuliaRatihNur.Indahsari@Panamas.com", phone: "085750687605" },
    pic2: { name: "Rohmana", email: "Rohmana.Rohmana@contracted.sampoerna.com", phone: "081288278470" },
    remarks: "ARA TANGERANG",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Tangerang 15117",
      kecamatan: "Tangerang",
      alamat: "Komplek Argo Pantes, Jl. MH Thamrin KM. 4 RT. 007 RW. 001 Kelurahan Cikokol Kecamatan Tangerang, Kota Tangerang 15117",
      kodePos: "15117",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Banda Aceh",
    subArea: "Banda Aceh",
    pic1: { name: "Haris Afzal", email: "haris.afzal@panamas.com", phone: "85277427815" },
    pic2: { name: "Abdul Haris", email: "Abdul.Haris@sampoerna.com", phone: "08116734234" },
    remarks: "PIC 1: ARA; PIC 2: SRE",
    note: "",
    shippingAddress: {
      provinsi: "Aceh",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. T. Imum Lueng Bata No.9 - Panteriek, Banda Aceh",
      kodePos: "",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Banda Aceh",
    subArea: "DPC Meulaboh",
    pic1: { name: "Asep Soemantri Jaya Wiguna", email: "asep.jayawiguna@panamas.com", phone: "8116251120" },
    pic2: { name: "Jackie Weenas", email: "jackie.weenas@sampoerna.com", phone: "085260022165" },
    remarks: "PIC 1: SPV DPC; PIC 2: SRE",
    note: "",
    shippingAddress: {
      provinsi: "Aceh",
      kotaKabupaten: "Aceh Barat",
      kecamatan: "Johan Pahlawan Kab. Aceh Barat",
      alamat: "Jl. Sisingamangaraja Kel. Gampa Kec. Johan Pahlawan  Kab. Aceh Barat",
      kodePos: "",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Kisaran",
    subArea: "DPC Rantau Prapat",
    pic1: { name: "Rudy Ady Putra", email: "ruddyady.putra@panamas.com", phone: "811626223" },
    pic2: { name: "Endika Taufik Aulia", email: "EndikaTaufik.Aulia@contracted.sampoerna.com", phone: "08116282597" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Rantau Prapat 21441)",
      kecamatan: "Rantau Utara",
      alamat: "PT HM Sampoerna. Tbk (Jl. Karya Bakti No 6 Keluaran Aek Paing, Kec Rantau Utara, Kota Rantau Prapat 21441)",
      kodePos: "21441",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Kisaran",
    subArea: "Kisaran",
    pic1: { name: "M. Reza Fahlevi", email: "m.reza.fahlevi@panamas.com", phone: "81360022904" },
    pic2: { name: "Muhammad Fri Hatta", email: "MuhammadFri.Hatta@contracted.sampoerna.com", phone: "085360979758" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Kisaran Barat",
      kecamatan: "Kota Kisaran Barat",
      alamat: "PT HM Sampoerna, Tbk (Jl. Jend Sudirman LK I Kel Bunut, Kec. Kota Kisaran Barat, kab. Asahan 21261)",
      kodePos: "21261",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Lhokseumawe",
    subArea: "DPC Langsa",
    pic1: { name: "Harish Mardi", email: "harish.mardi@panamas.com", phone: "82165703606" },
    pic2: { name: "Andy Safrizal", email: "andy.syafrizal@contracted.sampoerna.com", phone: "085261395234" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jln. Ahmad Yani No. 123 Gampong Paya Bujok Seuleumak Langsa 24115",
      kodePos: "24115",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Lhokseumawe",
    subArea: "Lhokseumawe",
    pic1: { name: "Harish Mardi", email: "harish.mardi@panamas.com", phone: "82165703606" },
    pic2: { name: "Muhammad Iqbal", email: "muhammad.iqbal@contracted.sampoerna.com", phone: "08116701372" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "Aceh",
      kotaKabupaten: "",
      kecamatan: "Muara Dua - Lhokseumawe 24352",
      alamat: "Jln. Medan - Banda Aceh Km. 2.72 Meunasah Panggoi Kec. Muara Dua - Lhokseumawe 24352",
      kodePos: "24352",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Medan 1",
    subArea: "DPC Langkat",
    pic1: { name: "Abdul Khalid", email: "Abdul.Khalid@panamas.com", phone: "81280449937" },
    pic2: { name: "Mira Harahap", email: "Mira.Harahap@contracted.sampoerna.com", phone: "081370323590" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "Medan Helvetia",
      alamat: "Jl. Gatot Subroto 152-154, Kel. Sei Sikambing, Kec. Medan Helvetia, Medan",
      kodePos: "",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Medan 1",
    subArea: "Medan 1",
    pic1: { name: "Abdul Khalid", email: "Abdul.Khalid@panamas.com", phone: "81280449937" },
    pic2: { name: "Mira Harahap", email: "Mira.Harahap@contracted.sampoerna.com", phone: "081370323590" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "Medan Helvetia",
      alamat: "Jl. Gatot Subroto 152-154, Kel. Sei Sikambing, Kec. Medan Helvetia, Medan",
      kodePos: "",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Medan 2",
    subArea: "Medan 2",
    pic1: { name: "Jimmy Sipanangi Aritonang", email: "jimmysipanangi.aritonang@panamas.com", phone: "8117450589" },
    pic2: { name: "mhd Azhari", email: "mhd.azhari@contracted.sampoerna.com", phone: "082381814481" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Kawasan Industri Medan Star, Jl.Pelita Raya Kav 15,No.117 Tanjung Morawa - Deli Serdang 20362",
      kodePos: "20362",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Padang Sidempuan",
    subArea: "DPC Sibolga",
    pic1: { name: "Zulkipli Perangin angin", email: "Zulkifli.Peranginangin@panamas.com", phone: "811681081" },
    pic2: { name: "Dicky Febrianda", email: "dicky.febrianda@contracted.sampoerna.com", phone: "081370014787" },
    remarks: "PIC 1: SPV DPC; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "Sumatera Utara",
      kotaKabupaten: "",
      kecamatan: "Pandan Tapanuli Tengah - Sumatera Utara 22616",
      alamat: "Jl.Raya PSP-Sibolga No.157 Kel.Sibuluan Nalambok Kec. Pandan Tapanuli Tengah - Sumatera Utara 22616",
      kodePos: "22616",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Padang Sidempuan",
    subArea: "EZD Nias",
    pic1: { name: "Zulkipli Perangin angin", email: "Zulkifli.Peranginangin@panamas.com", phone: "811681081" },
    pic2: { name: "Dicky Febrianda", email: "dicky.febrianda@contracted.sampoerna.com", phone: "081370014787" },
    remarks: "PIC 1: SPV DPC; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "",
      kodePos: "",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Padang Sidempuan",
    subArea: "Padang Sidempuan",
    pic1: { name: "Riston Ekasura Kembaren", email: "ristonekasura.kembaren@panamas.com", phone: "8116258310" },
    pic2: { name: "Supri Harahap", email: "supri.supri@contracted.sampoerna.com", phone: "085261334581" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "Hutaimbaru Padang Sidempuan Sumatra Utara 22711",
      alamat: "Jl. Merdeka No. 484 Kel. Losung Batu Kec. Hutaimbaru Padang Sidempuan  Sumatra Utara  22711",
      kodePos: "22711",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Pematang Siantar",
    subArea: "Pematang Siantar",
    pic1: { name: "Bernie Berninson Situmorang", email: "bernie.situmorang@panamas.com", phone: "8122683008" },
    pic2: { name: "Muhammad Fari", email: "Muhammad.Fari@contracted.sampoerna.com", phone: "085321777713" },
    remarks: "PIC 1: ARA; PIC 2: ADW",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Pematangsiantar",
      kecamatan: "Siantar Martoba Kota Pematangsiantar",
      alamat: "Jl. Medan KM 6,5 no 234 Simpang Karang Sari Kelurahan Pondok Sayur Kecamatan Siantar Martoba Kota Pematangsiantar",
      kodePos: "",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 1",
    area: "Tanah Karo",
    subArea: "Tanah Karo",
    pic1: { name: "Doni Pandapotan Simangunsong", email: "doni.pandapotansimangunsong@panamas.com", phone: "82246788896" },
    pic2: { name: "Hidayat Muhammad Nur", email: "MuhammadNur.Hidayat@contracted.sampoerna.com", phone: "08126366075" },
    remarks: "PIC 1: ARA ; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "Sumatera Utara",
      kotaKabupaten: "Karo 22111 Sumatera Utara",
      kecamatan: "Kabanjahe Kab. Karo 22111 Sumatera Utara",
      alamat: "Jl. Jamin Ginting No. 98A; Desa Ketaren Kec. Kabanjahe Kab. Karo 22111 Sumatera Utara",
      kodePos: "22111",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 2",
    area: "Air Molek",
    subArea: "Air Molek",
    pic1: { name: "Rayhan Lingga Kusumayudha", email: "rayhan.linggakusumayudha@panamas.com", phone: "8116902707" },
    pic2: { name: "Yulis Indah Pratiwi", email: "yulisindah.pratiwi@contracted.sampoerna.com", phone: "62852 7101 7707" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "Pasir Penyu",
      alamat: "PT. HM Sampoerna, Tbk (Depan Hotel Simpang Raya Air Molek)  Jl. Jend. Sudirman RT.01  RW.01 Kel. Tanjung Gading  Kec. Pasir Penyu, Air Molek, INHU - RIAU  29352",
      kodePos: "29352",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 2",
    area: "Batam",
    subArea: "Batam",
    pic1: { name: "Rizki Rosandi", email: "rizki.rosandi@panamas.com", phone: "8114009790" },
    pic2: { name: "Helmi", email: "helmi.helmi@contracted.sampoerna.com", phone: "6281 2679 3171" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "29461",
      kecamatan: "Batam Kota 29461",
      alamat: "Kompleks Sarana Industrial Point; Batam Center; Jl. Engku Putri No. 1 & 2, Blok B; Kel. Belian Kec. Batam Kota 29461",
      kodePos: "29461",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 2",
    area: "Bukittinggi",
    subArea: "Bukittinggi",
    pic1: { name: "Dyah Nurul Hapsari", email: "dyahnurul.hapsari@panamas.com", phone: "81119095555" },
    pic2: { name: "Melki busra", email: "melki.busra@contracted.sampoerna.com", phone: "62831 8244 5079" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "aur birugo tigo baleh",
      alamat: "PT HM Sampoerna TBK jalan prof M. Yamin RW III kel.aur kuning, kec aur birugo tigo baleh, bukittinggi",
      kodePos: "",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 2",
    area: "Duri",
    subArea: "Duri",
    pic1: { name: "Hengky Irawan", email: "hengky.irawan@panamas.com", phone: "8117060669" },
    pic2: { name: "Tri Sujarwadi", email: "Tri.Sujarwadi@sampoerna.com", phone: "62813 7409 1843" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "Riau",
      kotaKabupaten: "",
      kecamatan: "Mandau. Bengkalis. Riau. 28884.",
      alamat: "PT. HM. Sampoerna Office Duri. Jl. Stadion No. 01, RT04 /RW 06; Kel. Air Jamban, Kec. Mandau. Bengkalis. Riau. 28884.",
      kodePos: "28884",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 2",
    area: "Padang",
    subArea: "DPC Solok",
    pic1: { name: "Tomy Ardiyono", email: "tomy.ardiyono@panamas.com", phone: "6281 2702 6369" },
    pic2: { name: "Syuman Hario", email: "hario.syuman@contracted.sampoerna.com", phone: "0282249085425" },
    remarks: "PIC 2: Spc DPC ; PIC 1: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "Sumatera Barat",
      kotaKabupaten: "Solok - Provinsi Sumatera Barat",
      kecamatan: "Lubuk Sikarah -Kota Solok - Provinsi Sumatera Barat",
      alamat: "PT HM Sampoerna DPC Solok-Jl. Bypass KTK Sutan Pamuncak  -Kel. KTK, Kec. Lubuk Sikarah -Kota Solok - Provinsi Sumatera Barat",
      kodePos: "",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 2",
    area: "Padang",
    subArea: "Padang",
    pic1: { name: "M. Bagus Rahmatullah", email: "m.bagus.rahmatullah@panamas.com", phone: "81259063710" },
    pic2: { name: "Joni Hermanto", email: "Joni.Hermanto@contracted.sampoerna.com", phone: "62 852 12129234" },
    remarks: "PIC 2: ARA; PIC 1: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "Sumatera Barat",
      kotaKabupaten: "",
      kecamatan: "Koto Tangah -Kodya Padang - Provinsi Sumatera Barat - 25176",
      alamat: "PT HM Sampoerna Padang-Jl. Bypass Teluk Bayur Km16, RT02/RW06 -Kel. Koto Panjang Ikur Koto, Kec. Koto Tangah -Kodya Padang - Provinsi Sumatera Barat - 25176",
      kodePos: "25176",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 2",
    area: "Pekanbaru",
    subArea: "Pekanbaru",
    pic1: { name: "Sitti Fachramia Faza", email: "sittifachramia.faza@panamas.com", phone: "81917559100" },
    pic2: { name: "Afrida Lubis", email: "afrida.lubis@contracted.sampoerna.com", phone: "62812 4137 0293" },
    remarks: "PIC 1: ARA; PIC 2: Team Logistic",
    note: "",
    shippingAddress: {
      provinsi: "Riau",
      kotaKabupaten: "Pekanbaru",
      kecamatan: "Marpoyan Damai",
      alamat: "Jl. Arifin Ahmad No. 99, Kelurahan Tangkerang Tengah, Kecamatan Marpoyan Damai, Kota Pekanbaru, Riau, 28282",
      kodePos: "28282",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 2",
    area: "Tanjung Pinang",
    subArea: "EZD Tanjung Balai Karimun",
    pic1: { name: "Trisna Wijaya", email: "trisna.wijaya@panamas.com", phone: "8127917344" },
    pic2: { name: "Trisna Wijaya", email: "Trisna.Wijaya@sampoerna.com", phone: "08127917344" },
    remarks: "PIC 1: SPT; PIC 2: SPT",
    note: "",
    shippingAddress: {
      provinsi: "Riau",
      kotaKabupaten: "",
      kecamatan: "Tebing",
      alamat: "Kantor Rokok Sampoerna /PT. Pratama Indah Makmur Jl. Nangka, Komplek Bukit Merah, RT. 002 RW. 001 Kel Harjosari, Kec Tebing, Kab, Karimun 29661 Kepulauan Riau Telp. 0777 - 3624557",
      kodePos: "29661",
    },
  },
  {
    zone: "North Sumatera",
    region: "Sumatera 2",
    area: "Tanjung Pinang",
    subArea: "Tanjung Pinang",
    pic1: { name: "Firman Martadinata", email: "firman.martadinata@panamas.com", phone: "8127379057" },
    pic2: { name: "Anjelita Salassa", email: "anjelita.salassa@sampoerna.com", phone: "08115111736" },
    remarks: "PIC 1: SPT; PIC 2: SPT",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "piring kecamatan tanjung pinang timur - KEPRI",
      kecamatan: "tanjung pinang timur - KEPRI",
      alamat: "PT.Pratama Indah Makmur Jl. Kijang lama (sebelah kantor disdukcapil) RT 003 RW 002 kelurahan melayu kota piring kecamatan tanjung pinang timur - KEPRI",
      kodePos: "",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 3",
    area: "Jambi",
    subArea: "Jambi",
    pic1: { name: "Nurdiansyah, Agus", email: "agus.nurdiansyah@panamas.com", phone: "081373634400" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "Jambi",
      kotaKabupaten: "",
      kecamatan: "Jambi Selatan",
      alamat: "Komplek Pergudangan PT KLM, Jl. Lingkar Selatan I RT 30 Kav.; 07, Kel. Paal Merah Kec. Jambi Selatan",
      kodePos: "",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 3",
    area: "Lahat",
    subArea: "DPC Baturaja",
    pic1: { name: "Rehatta, Arie Nathaniel", email: "arienathaniel.rehatta@panamas.com", phone: "081319611975" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Terrritory Analyst",
    note: "",
    shippingAddress: {
      provinsi: "Sumatera Selatan",
      kotaKabupaten: "Ogan Komering Ulu. Prov. Sumsel",
      kecamatan: "Baturaja Timur",
      alamat: "Jl. Garuda RT/RW 03 Dusun VII, Desa Air Paoh, Kec. Baturaja Timur, Kab. Ogan Komering Ulu. Prov. Sumsel",
      kodePos: "",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 3",
    area: "Lahat",
    subArea: "Lahat",
    pic1: { name: "Rehatta, Arie Nathaniel", email: "arienathaniel.rehatta@panamas.com", phone: "081319611975" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Terrritory Analyst",
    note: "",
    shippingAddress: {
      provinsi: "Sumatera Selatan",
      kotaKabupaten: "Lahat. Prov. Sumsel",
      kecamatan: "Lahat",
      alamat: "Jl. Baru Lintas Sumatera Desa Manggul Kec. Lahat, Kab. Lahat. Prov. Sumsel",
      kodePos: "",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 3",
    area: "Muara Bungo",
    subArea: "Muara Bungo",
    pic1: { name: "Siagian, Vyvian", email: "Vyvian.Siagian@panamas.com", phone: "+62 822-7721-2659" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "Jambi",
      kotaKabupaten: "Bungo Prov. Jambi Kode Pos 37214",
      kecamatan: "Rimbo Tengah Kab. Bungo Prov. Jambi Kode Pos 37214",
      alamat: "PT. HM Sampoerna, Tbk. Jalan Soekarno-Hatta, RT 005/RW 000 Dusun Sungai Mengkuang Kec. Rimbo Tengah Kab. Bungo Prov. Jambi Kode Pos 37214",
      kodePos: "37214",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 3",
    area: "Palembang 1",
    subArea: "Palembang 1",
    pic1: { name: "Malingkas, Daviensya Giovancha Anabel", email: "daviensyagiovanchaanabel.malingkas@panamas.com", phone: "081180001311" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Komplek Pergudangan Palembang Star No 9; Jl. Letjen Harun Sohar ( Tanjung api-api) Km 1,3; Kel. Kebun Bunga Palembang 30154",
      kodePos: "30154",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 3",
    area: "Palembang 2",
    subArea: "Palembang 2",
    pic1: { name: "Yogiswara, Ketut", email: "Ketut.Yogiswara@panamas.com", phone: "+62 852-6885-5558" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "Sumatera Selatan",
      kotaKabupaten: "Ogan Komering Ilir",
      kecamatan: "Kayu Agung",
      alamat: "Kantor Palembang 2. PT. HM Sampoerna Tbk, Jl. Lintas Timur (Depan Komplek Villa Kuda Mas Palembang), Desa Muara Baru, Kec. Kayu Agung, Kab. Ogan Komering Ilir, Sumatera Selatan",
      kodePos: "",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 3",
    area: "Pangkal Pinang",
    subArea: "EZD Bangka",
    pic1: { name: "Rahman, Agus Faisal", email: "agus.rahman@panamas.com", phone: "08127217119" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Terrritory Analyst",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Bumi RT/RW 001/003",
      kecamatan: "Rangkui Pangkal Pinang Babel",
      alamat: "Jl. Kota Bumi  RT/RW 001/003; Kel. Gajah Mada, Kec. Rangkui Pangkal Pinang Babel",
      kodePos: "",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 3",
    area: "Pangkal Pinang",
    subArea: "EZD Belitung",
    pic1: { name: "Suwarto, Rudi", email: "rudi.suwarto@panamas.com", phone: "08127419990" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "SPV Distribution",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "Tanjung Pandan Belitung 33412.",
      alamat: "Jl jend Sudirman RT 08 RW 04 Lantai 2 Samping BCA Kelurahan Pangkal Lalang Kec Tanjung Pandan Belitung 33412.",
      kodePos: "33412",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 4",
    area: "Bandar Lampung",
    subArea: "Bandar Lampung",
    pic1: { name: "Setiana, Deny Eka", email: "deny.setiana@panamas.com", phone: "08126250234" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "Lampung",
      kotaKabupaten: "Bandar Lampung 35122",
      kecamatan: "Sukabumi",
      alamat: "Komplek Pergudangan Vast Land Jl. Tembesu No. 7, Kel. Campang Raya, Kec. Sukabumi, Kota Bandar Lampung 35122",
      kodePos: "35122",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 4",
    area: "Bandar Lampung",
    subArea: "DPC Kalianda",
    pic1: { name: "", email: "", phone: "" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "",
      kodePos: "",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 4",
    area: "Bandar Lampung",
    subArea: "DPC Pringsewu",
    pic1: { name: "Setiana, Deny Eka", email: "deny.setiana@panamas.com", phone: "08126250234" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Pringsewu 35372",
      kecamatan: "Gading Rejo",
      alamat: "Jl. Raya Pringsewu - Tj. Karang, Desa Tambak Rejo, Kec. Gading Rejo, Kab. Pringsewu 35372",
      kodePos: "35372",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 4",
    area: "Bengkulu",
    subArea: "Bengkulu",
    pic1: { name: "Wijaya, Anastasia Lioni", email: "anastasialioni.wijaya@panamas.com", phone: "082384385282" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "Bengkulu",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. Kalimantan RT12/RW04 Kel. Rawa Makmur Bengkulu  38121",
      kodePos: "38121",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 4",
    area: "Bengkulu",
    subArea: "DPC Lubuk Linggau",
    pic1: { name: "Wijaya, Anastasia Lioni", email: "anastasialioni.wijaya@panamas.com", phone: "082384385282" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Jl. Fatmawati Kelurahan Taba Jemekeh, Kecamatan Lubuklinggau Timur 1, Kota Lubuk Linggau",
      kodePos: "",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 4",
    area: "Kotabumi",
    subArea: "DPC Tulang Bawang",
    pic1: { name: "Saputra, Reno", email: "Reno.Saputra@panamas.com", phone: "+62 821-8286-2415" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Tulang Bawang 34682",
      kecamatan: "Banjar Agung Kab Tulang Bawang 34682",
      alamat: "Jl. Lintas Timur RT 003/RW 004 Kampung Banjar Agung Kec. Banjar Agung Kab Tulang Bawang 34682",
      kodePos: "34682",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 4",
    area: "Kotabumi",
    subArea: "Kotabumi",
    pic1: { name: "Saputra, Reno", email: "Reno.Saputra@panamas.com", phone: "+62 821-8286-2415" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "Lampung",
      kotaKabupaten: "",
      kecamatan: "Kotabumi Selatan Lampung Utara 34511",
      alamat: "Jl. Sukarno-Hatta  No.179A RT03 / RW06 Kel. Tanjung Harapan Kec. Kotabumi Selatan Lampung Utara 34511",
      kodePos: "34511",
    },
  },
  {
    zone: "South Sumatera",
    region: "Sumatera 4",
    area: "Metro",
    subArea: "Metro",
    pic1: { name: "Purba, Andri", email: "andri.purba@panamas.com", phone: "08117992422" },
    pic2: { name: "", email: "", phone: "" },
    remarks: "Area Retail Analyst",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "Office PT. HM Sampoerna Tbk Area Metro, Jalan AH Nasution 30A Desa Adirejo Kecamatan Pekalongan Lampung Timur, Lampung",
      kodePos: "",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Bandung 1",
    subArea: "Bandung 1",
    pic1: { name: "Tanjung, Arum", email: "tanjung.arum@panamas.com", phone: "85794226884" },
    pic2: { name: "Toto iskandar", email: "toto.iskandar@contracted.sampoerna.com", phone: "89519712133" },
    remarks: "ARA",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Bandung Jawabarat 40293",
      kecamatan: "ujung berung kota Bandung Jawabarat 40293",
      alamat: "PT. HM Sampoerna Tbk Bandung1, Jl. Soekarno Hatta no 795 kelurahan cisaranten wetan kecamatan ujung berung kota Bandung Jawabarat 40293",
      kodePos: "40293",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Bandung 2",
    subArea: "Bandung 2",
    pic1: { name: "Yahfi, Muhammad Alfi", email: "muhammadalfi.yahfi@panamas.com", phone: "82216768893" },
    pic2: { name: "Toto iskandar", email: "toto.iskandar@contracted.sampoerna.com", phone: "89519712133" },
    remarks: "ARA",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Bandung Jawabarat 40293",
      kecamatan: "ujung berung kota Bandung Jawabarat 40293",
      alamat: "PT. HM Sampoerna Tbk Bandung2, Jl. Soekarno Hatta no 795 kelurahan cisaranten wetan kecamatan ujung berung kota Bandung Jawabarat 40293",
      kodePos: "40293",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Bandung 2",
    subArea: "DPC Sumedang",
    pic1: { name: "Sugiri, ARIE", email: "ARIE.Sugiri@panamas.com", phone: "81218316781" },
    pic2: { name: "Arifudin, Muhammad", email: "Muhammad.Arifudin@contracted.sampoerna.com", phone: "8987995955" },
    remarks: "SRE",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Barat",
      kotaKabupaten: "Seme.",
      kecamatan: "Sume. Utara",
      alamat: "PT HM Sampoerna Tbk, Jl. Sebelas April No.84, Desa Ranca Mulya; Kec. Sume. Utara, Kab. Seme.,  Sumedang 45321, Jawa Barat",
      kodePos: "45321",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Bandung 3",
    subArea: "Bandung 3",
    pic1: { name: "Heryanto, Heryanto", email: "heryanto.heryanto@panamas.com", phone: "816625328" },
    pic2: { name: "Tedi Sahrudin", email: "tedi.sahrudin@contracted.sampoerna.com", phone: "81320405558" },
    remarks: "ARA",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "subang",
      kecamatan: "subang kab subang",
      alamat: "PT HM Sampoerna Tbk, Jl. Otto iskandar dinata no.234 kel sukamelang kecamatan subang kab subang",
      kodePos: "",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Bandung 3",
    subArea: "DPC Padalarang",
    pic1: { name: "Heryanto, Heryanto", email: "heryanto.heryanto@panamas.com", phone: "816625328" },
    pic2: { name: "Toto iskandar", email: "toto.iskandar@contracted.sampoerna.com", phone: "89519712133" },
    remarks: "ARA",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Bandung Jawabarat 40293",
      kecamatan: "ujung berung kota Bandung Jawabarat 40293",
      alamat: "PT HM Sampoerna Tbk DPC Padalarang, Jl. Soekarno Hatta no 795 kelurahan cisaranten wetan kecamatan ujung berung kota Bandung Jawabarat 40293",
      kodePos: "40293",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Cirebon",
    subArea: "Cirebon",
    pic1: { name: "Kusumardiana, Muhammad Ryan", email: "muhammadryan.kusumardiana@panamas.com", phone: "6,28122E+12" },
    pic2: { name: "Farhan", email: "Farhan.Farhan@contracted.sampoerna.com", phone: "81313030197" },
    remarks: "ARA",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Cirebon kode pos 45153",
      kecamatan: "Kedawung",
      alamat: "PT HM Sampoerna Tbk, Jl. Pilang Raya No. 90 A RT. 001 RW. 001; Kel. Pilang Sari, Kec. Kedawung, Kabupaten Cirebon kode pos 45153",
      kodePos: "45153",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Cirebon",
    subArea: "DPC Indramayu",
    pic1: { name: "Kusumardiana, Muhammad Ryan", email: "muhammadryan.kusumardiana@panamas.com", phone: "6,28122E+12" },
    pic2: { name: "Walivian Hidayat", email: "Walivian.Hidayat@contracted.sampoerna.com", phone: "85862811669" },
    remarks: "ARA",
    note: "",
    shippingAddress: {
      provinsi: "",
      kotaKabupaten: "Indramayu kode pos 45221",
      kecamatan: "Sindang Kab. Indramayu kode pos 45221",
      alamat: "PT HM Sampoerna Tbk, Jl. Rambatan Wetan RT.14 RW.04 Blok B; Desa Rambatan Wetan Kec. Sindang Kab. Indramayu kode pos 45221",
      kodePos: "45221",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Garut",
    subArea: "Garut",
    pic1: { name: "Filely, Vivian", email: "vivian.filely@panamas.com", phone: "85729448833" },
    pic2: { name: "Mustofa, Agung", email: "agung.mustofa@contracted.sampoerna.com", phone: "82126399020" },
    remarks: "ARA",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Barat",
      kotaKabupaten: "Wetan Kecamatan Garut Kota Kabupaten Garut Propinsi Jawa Barat 44111",
      kecamatan: "Garut Kota Kabupaten Garut Propinsi Jawa Barat 44111",
      alamat: "PT HM Sampoerna Tbk, Jl. Tegal Kurdi No 99A Kelurahan Kota Wetan Kecamatan Garut Kota Kabupaten Garut Propinsi Jawa Barat 44111",
      kodePos: "44111",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Sukabumi",
    subArea: "DPC Cianjur",
    pic1: { name: "Juhri, Yopie", email: "yopie.juhri@panamas.com", phone: "811232583" },
    pic2: { name: "Minarrohman, Mohammad Amin", email: "mohammadamin.minarrohman@contracted.sampoerna.com", phone: "85863227999" },
    remarks: "SRE",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Barat",
      kotaKabupaten: "Cianjur",
      kecamatan: "Warungkondang",
      alamat: "PT HM Sampoerna Tbk, Jl. Raya Sukabumi Km. 6, Desa Ciwalen, Kec. Warungkondang, Kabupaten Cianjur, Jawa Barat 43261",
      kodePos: "43261",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Sukabumi",
    subArea: "Sukabumi",
    pic1: { name: "Wibisono, Genta", email: "genta.wibisono@panamas.com", phone: "6,28562E+12" },
    pic2: { name: "Deny Halim", email: "Deny.Halim@contracted.sampoerna.com", phone: "81220829868" },
    remarks: "ARA",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Barat",
      kotaKabupaten: "Sukabumi",
      kecamatan: "Cibereum",
      alamat: "PT HM Sampoerna Tbk, Jl. Pembangunan No. 9, Kel. Babakan, Kec. Cibereum, Kota Sukabumi, Jawa Barat 43142",
      kodePos: "43142",
    },
  },
  {
    zone: "West Java",
    region: "Java 1",
    area: "Tasikmalaya",
    subArea: "Tasikmalaya",
    pic1: { name: "Fitriyadi, Deni", email: "deni.fitriyadi@panamas.com", phone: "81321641818" },
    pic2: { name: "Adie Cahyadi", email: "Adie.Cahyadie@contracted.sampoerna.com", phone: "89624420177" },
    remarks: "ARA",
    note: "",
    shippingAddress: {
      provinsi: "Jawa Barat",
      kotaKabupaten: "",
      kecamatan: "",
      alamat: "PT HM Sampoerna Tbk, Komplek Rukan TFT Blok E-234, Jalan Ir. H. Juanda No. 18, Linggajaya, Mangkubumi, Linggajaya, Mangkubumi, Tasikmalaya, Jawa Barat 46181",
      kodePos: "46181",
    },
  },
];

